server:
  file:
    upload: D:\Code\Java\cool\demo\upload
    visit: http://192.168.1.165:7032/static

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

spring:
  web:
    resources:
      # 设置静态资源的存放路径
      static-locations: file:${server.file.upload}
  mvc:
    # 静态资源的访问路径，默认 /
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/cool?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
  data:
    redis:
      redis:
        host: 127.0.0.1
        port: 6379
        database: 0


logging:
  config: classpath:log4j2-prod.xml
  file:
    path: logs