server:
  upload: D:\Code\Java\cool\cool-core-test

spring:
  # 设置静态资源的存放路径
  resources:
    static-locations: classpath:/static
  datasource:
    url: jdbc:mysql://localhost:3306/cool?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root

logging:
  config: classpath:log4j2-prod.xml
  file:
    path: logs/${spring.application.name}

knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: true